"""Provider-neutral AI Gateway contract and offline reference runtime."""

from aieos.ai_gateway.gateway import (
    Acceptance,
    AIGateway,
    AIInvocationRequest,
    AIInvocationResponse,
    AIUsage,
    ContextItem,
    InvocationState,
    ModelCatalogEntry,
    ProviderAdapter,
    ProviderEffectBoundary,
    ProviderFailure,
    ProviderResult,
    ProviderStreamEvent,
    ReferenceAIGateway,
    ReferenceGatewayStore,
    ResponseMode,
    RouteDecision,
    StreamChunk,
)
from aieos.ai_gateway.prompt_pipeline import (
    AssembledPrompt,
    PackageState,
    PromptPackage,
    PromptPackageCatalog,
)

__all__ = (
    "AIGateway",
    "AIInvocationRequest",
    "AIInvocationResponse",
    "AIUsage",
    "Acceptance",
    "AssembledPrompt",
    "ContextItem",
    "InvocationState",
    "ModelCatalogEntry",
    "PackageState",
    "PromptPackage",
    "PromptPackageCatalog",
    "ProviderAdapter",
    "ProviderEffectBoundary",
    "ProviderFailure",
    "ProviderResult",
    "ProviderStreamEvent",
    "ReferenceAIGateway",
    "ReferenceGatewayStore",
    "ResponseMode",
    "RouteDecision",
    "StreamChunk",
)
